# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07ae4cbfc8af3fedf84f2938635fd54fb65bb3cd043864cf95b8005684a5909fcb8889bc3ae497181a9ef1a875f134e871134ad1ec22055794c16196dc613b0e

test:
  secret_key_base: 77de13f27d6ad81db8cf0ece1ae2291f70bc5ea806355be450fbcadc28aed3adf07cff7ae44e3bba94d27fe052976a0ec18a5d5b943a540dbd5e8944957345fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
